// Generated by scripts/sync-pdf-signer-config.mjs. Edit browser-extension/pdf-signer-bridge/pdf-signer.config.json instead.
export const PDF_SIGNER_EXTENSION_ID = "kcblmjckgngeaemhkcaoklligaollnec";
export const PDF_SIGNER_EXTENSION_INSTALL_URL = "/browser-extension/pdf-signer-bridge/README.md";
